### ISSUE TITLE
Running saucectl-run-action in GitHub Actions for Playwright tests using "env" in the YAML configuration is not working properly for "macOS"

### ISSUE THREAD

**Issue by jpaxtonrs** [saucelabs/saucectl-run-action#19]
I am currently using the `saucectl-run-action` GitHub Action to run my `Playwright` tests in `SauceLabs`.
I am passing `env` variables from the GitHub Actions like so:
```
 - name: Run saucectl with Playwright tests
   uses: saucelabs/saucectl-run-action@v2
   with:
      sauce-username: ${{ secrets.SAUCE_USERNAME }}
      sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
      region: ${{ secrets.SAUCE_REGION }}
      config-file: .sauce/config.yml
      concurrency: 10
   env: |
      NODE_ENV=dev # This is just an example value.
      ...
```

All my tests are running with the environment variables perfectly fine against `Windows` machines in `SauceLabs`.
However, when I run the same setup against `macOS`, the environment variables are not being passed in correctly. Even the same test suite is failing for `macOS`, while it passes for `Windows`. Here is the `suites` portion of the `.sauce/config.yml`:
```
suites:
  - name: "FOOBAR - Firefox"
    platformName: "Windows 11"
    screenResolution: "1440x900"
    testMatch: [ tests\/foobar\/(.*).ts ]
    params:
      browserName: "firefox"
      project: "firefox"

  - name: "FOOBAR - MacOS Chromium"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: [ tests\/foobar\/(.*).ts ]
    params:
      browserName: "chromium"
      project: "chromium"
```

While debugging the `.sauce/config.yml`, I found something very interesting. I tried the following:
```
env:
  environment: $NODE_ENV # should print "dev" from the GitHub Action snippet above - "dev" for macOS as expected
  Environment: $NODE_ENV # should print "dev" from the GitHub Action snippet above - "undefined" for macOS
  NODE_ENV: $NODE_ENV # should print "dev" from the GitHub Action snippet above - "undefined" for macOS
  ...
```
When running the above `.sauce/config.yml` against the `Windows` machine, the expected `"dev"` being printed for all environment variables above worked as expected. 
However, when running the above `.sauce/config.yml` against the `macOS`, it **only** prints the expected `"dev"` value for `process.env.environment` (lower-case) and NOT `process.env.Environment` and `process.env.NODE_ENV`. 
I am not sure why the values would be different as they are all getting their values from the same source - `$NODE_ENV` from the GitHub Workflow file. It seems like `macOS` is only working for environment variables that are lower-case.

This issue seems to be specific to the GitHub Action as it does not occur when I run it from my local. When I run the following command, for both `Windows` and `macOS` it works:
```
npx saucectl run -e  NODE_ENV=dev
```

Thanks!

**Comment by jpaxtonrs** [comment]
**Update:**

While debugging a bit more, I printed out the contents of `process.env` for the `macOS` and it looks like it is turning all of the upper-case environment variables declared from the GitHub Action workflow file and doing a `.toLowerCase` somewhere.

For example, `NODE_ENV` turned into `node_env` only for the `macOS`.

When I did a `console.log(process.env)`, here was part of the output for the `macOS`:
```
{
  ...
  node_env: 'dev',
  ...
}
```

Whereas, with `Windows`, like mentioned, it is working and is properly printing out `NODE_ENV: 'dev'`

**Comment by tianfeng92** [comment]
Hi @jpaxtonrs !
Thanks for reporting this issue and really appreciate your debugging. I checked your test settings and steps and here are several findings.
1. In config file, setting `env` in the root level is case insensitive. We're using [viper](https://github.com/spf13/viper) to parse config setting. It doesn't support case sensitive configuration key and will convert the key to lower case, [viper docs](https://pkg.go.dev/github.com/spf13/viper#readme-why-viper). This causes the inconsistency for `Windows` and `macOS` platforms cause on `Windows` it's case insensitive while `macOS` is not. 
  > Important: Viper configuration keys are case insensitive. There are ongoing discussions about making that optional.
2. Passing `env` from cli like `saucectl run -e FOO=BAR` is case sensitive. This should work on both `Windows` and `macOS` platform.
3. Setting `env` through github action like following should work on `Windows` and `macOS` both, e.g. https://github.com/tianfeng92/saucectl-playwright-example/actions/runs/3421799775/jobs/5698416603. `saucectl` github action is actually parsing the config and converting `env` setting like `saucectl run -e FOO=BAR -e my_foo=my_bar`
```
- name: Saucectl RUN
        uses: saucelabs/saucectl-run-action@v1
        with:
          concurrency: 10
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          env: |
            FOO=${{ secrets.FOO }}
            my_foo=${{ secrets.my_foo }}
```
test job links: 
https://app.saucelabs.com/tests/633cb2884d92498787106b7d11033020
https://app.saucelabs.com/tests/53bf48ff72b04af0a19ae961ab562b5c

4. In the config file, setting `env` in the suite level can be case sensitive. It shouldn't have problem on `macOS` platform. [sauce docs](https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#env-1).

The current workaround here is either passing the env through cli(github action setting) or setting `env` on suite level. We're continually discussing on resolving the root level `env` setting in the config file and I'll also add documentation to explain this issue.

Feel free to ask any question!
