### ISSUE TITLE
RequestError [HttpError]: API rate limit exceeded

### ISSUE THREAD

**Issue by leinardi** [saucelabs/saucectl-run-action#21]
Since last week we are starting to get some `API rate limit exceeded` errors when using this action.

This is the error:
```
Run saucelabs/saucectl-run-action@v2
/home/runner/work/_actions/saucelabs/saucectl-run-action/v2/dist/main/index.js:7761
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at /home/runner/work/_actions/saucelabs/saucectl-run-action/v2/dist/main/index.js:7761:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async selectCompatibleVersion (/home/runner/work/_actions/saucelabs/saucectl-run-action/v2/dist/main/index.js:16336:22)
    at async saucectlInstall (/home/runner/work/_actions/saucelabs/saucectl-run-action/v2/dist/main/index.js:16351:21)
    at async run (/home/runner/work/_actions/saucelabs/saucectl-run-action/v2/dist/main/index.js:16676:10) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/saucelabs/saucectl/releases',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
      connection: 'close',
      'content-length': '276',
      'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 23 Jan 2023 10:33:45 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'Varnish',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-ratelimit-limit': '60',
      'x-ratelimit-remaining': '0',
      'x-ratelimit-reset': '1674471352',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '60',
      'x-xss-protection': '1; mode=block'
    },
    data: {
      message: "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
      documentation_url: 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/saucelabs/saucectl/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.4 octokit-core.js/4.0.5 Node.js/16.13.0 (linux; x64)'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

The error states that `Authenticated requests get a higher rate limit`, but I think we are already using authenticated requests or, at least this is how we are starting the Action:

```yaml
      - name: Run PR Android test
        uses: saucelabs/saucectl-run-action@v2
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
          testing-environment: ''
          select-suite: 'PR_TEST'
```

Are we doing something wrong? How is it possible that we are already hitting the API limit? And why the error is stating that Authenticated requests get a higher rate limit?

**Comment by cameronbrandcoders** [comment]
Can confirm, I am seeing the same thing. One difference, I am authenticating with this action, and am running saucectl in a separate step.

```
- name: 'Authenticate Saucelabs'
        uses: saucelabs/saucectl-run-action@v2
        with:
          skip-run: true
          sauce-username: ${{ secrets.SAUCELABS_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCELABS_ACCESSKEY }}
```

then separately later in the action

```
- name: 'Run The Test'
  env:
    {stuff}
  run: saucectl run --config .sauce/sanity-test.yml --select-suite "$SUITE" --env latest=1 --env environment="$ENVIRONMENT" --env versionnumber="$VERSIONNUMBER" --env repository="$REPOSITORY" --env githubref="$GITHUBREF" --env githubsha="$GITHUBSHA" --env buildnumber="$BUILDNUMBER"
```
But the outcome is the same, occasionally I am seeing the api limit error.
