### ISSUE TITLE
Failed to retrieve build id for job () error="unexpected statusCode: 404"

### ISSUE THREAD

**Issue by SmialyKot** [saucelabs/saucectl-run-action#42]
## The Problem

The jobs started with this action are failing since 26.09 due to:
```
16:26:35 WRN Failed to retrieve build id for job () error="unexpected statusCode: 404"
16:26:35 ERR Failed to start suite. error="failed to retrieve job status for suite test-suite-id (shard 1/1): internal server error" 
```
The jobs are started on SauceLabs since I can see them execute just fine, but this action which should await results simply fails within 22 seconds with this error.

<img width="1225" alt="Zrzut ekranu 2024-09-29 o 16 38 25" src="https://github.com/user-attachments/assets/83099c3f-0444-4967-b480-921d0f25c65e">

I believe this issue intensifies when there are multiple queued tests (from different jobs) present at the same time.

## Environment

- saucectl-run-action@v4
- eu-central-1
- Ubuntu 22.04

## Code To Reproduce Issue [ Nice To Have ]

```
- name: Run tests
  uses: saucelabs/saucectl-run-action@v4
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    timeout: 240m
```
